############################################################
#
# web访问端口号 约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root123456
  hikari:
    connection-timeout: 30000     # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException
    minimum-idle: 5               # 最小连接数
    maximum-pool-size: 20         # 最大连接数
    auto-commit: true             # 自动提交
    idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP # 连接池名字
    max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
    connection-test-query: SELECT 1
  redis:
    # Redis 单机单实例
#    database: 1
#    host: localhost
#    port: 6379
#    password: 123456
    # Redis 哨兵模式
#    database: 1
#    password: 123456
#    sentinel:
#      master: mymaster
#      nodes: 192.168.1.191:26379,192.168.1.192:26379,192.168.1.193:26379
    # Redis 集群模式
    password: 123456
    cluster:
      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379
  servlet:
    multipart:
      max-file-size: 512000      # 文件上传大小限制为500kb
      max-request-size: 512000   # 请求大小限制为500kb
  session:
    store-type: redis

############################################################
#
# mybatis 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false  # 在进行数据库操作的时候，判断表达式 username != null, 是否追加 user != ''
  identity: MYSQL
mybatis:
  type-aliases-package: com.imooc.pojo        # 所有POJO类所在路径
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
