spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root123456
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.187:9300,192.168.1.188:9300,192.168.1.189:9300
      cluster-name: es-cluster